### ISSUE TITLE
Helping with this project

### ISSUE THREAD

**Issue by shaunakg** [JMSS-time/time-updated#4]
JMSS Time has been a really helpful part of my school life throughout my time as a JMSS student. I have experience in static web development as well as server-side technologies (although that's not needed). I believe I'm capable of maintaining this site to the standard that you have as its creators.

I checked the other issues here and I'd just like to answer the questions you've sent to the others in order to save a little bit of time.

**How much experience do you have making websites?**
I have been experimenting with web development for around 5 years. I have made websites that are both static HTML+CSS+JS as well as using libraries such as React in order to handle dynamic content display. You can check out my Github user for more information as well as this quick notion page that I set up: https://shaunakg.notion.site/131ea6d1959248c1b36973f3892fb4aa?v=2dfcb805f561407da7a91bce4781f170.

**Do you have an example project that you have worked on that closely resembles the technology stack used by JMSS-Time?** 
Yep. I actually made something similar to this at the end of Year 11, the Victorian Term date tracker. The Github repository for the code is here: https://github.com/vic-term/vic-term.github.io, and the core JS code logic resembles the one that you've used making JMSS time.

**Do you have any ideas for new features or sites that could supplement JMSS-Time? If so, please give a rough outline.**
I think the Victorian term countdown website's features could be implemented into this one for ease of use. 

Also, maybe sub-timers that people can add to give them countdowns towards various dates important to them (for example, a countdown to a major SAC). This would just be implemented in client-side `localStorage` so it wouldn't require any server technologies. Or it could be put in a query string so that you could embed the site into Notion or something as many people do. 

However I don't have any really major ideas, as your project is pretty much great in and as of itself.

Thanks (and enjoy university),
Shaunak

**Comment by ehne** [comment]
Hi Shaunak! 

Thanks for answering those questions! I believe that you and David would be great to run the JMSS-Time website.

It seems like you have a lot of experience with web development, and can make very nice websites indeed. Your suggestion of letting students create custom timers and countdowns is a great idea!

I'll invite you to the JMSS-Time organisation, and you should shortly receive an email from GitHub. 

Now, in terms of running the website, I wrote a whole massive document, but I'll spare you that mess. Here's the TL;DR:

- Keep the website (and any subsequent websites/features) fast, easy to use, and accurate.
- Use Vanilla JS and don’t rely on external libraries/frameworks. Try to keep it to one script request. (No analytics scripts)
- Check your algorithm’s efficiency and try to make the best possible one. No student likes dealing with a slow website.
- Use the Semistandard JS code style and linter to keep your code standardised and to spot bugs.
- Make sure that the website is as accurate as it can be. Students rely on JMSS-Time to tell them the truth.
- Make sure that the website is accessible and easy to use.
- Try to keep within the already laid out design conventions of JMSS-Time. Fairly monochrome on a vibrant blurred background. There is wiggle room here, just make it look nice, really.
- The colours used are from the [Tailwindcss colour palette](https://v2.tailwindcss.com/docs/customizing-colors) (except for white, which is #fff). The font used is IBM Plex Mono.
- Commits should be in the format of a [gitmoji](https://gitmoji.dev/) followed by what the commit does.

If you know what this stuff means, that's great. If not, it doesn't really matter. Just make it nice and keep the timetable up to date.

Thanks, and it's great to have you onboard :)
